### ISSUE TITLE
R-package shinyMlr

### ISSUE THREAD

**Issue by florianfendt** [mlr-org/shinyMlr#119]
I hacked together a little R-package to make life for people who wish to install our app locally a little bit easier. The package is in the branch "package" and the workflow to install and start shinyMlr is as follows:
```
devtools::install_github("mlr-org/shinyMlr", ref = "package")
library(shinyMlr)
# download a copy of the app to your machine
downloadShinyMlr()
# launch app
runShinyMlr()
```
@everyone especially @berndbischl 
opinions?
Plus: Does it make sense to upload this on CRAN or would that be obsolete anyway once we host the
app on a server?

**Comment by jakob-r** [comment]
I think we would never want to run this on our own server exclusively. If this is supposed to run fast and reliable for many people it's going to be expensive. Who want's to pay for that? A try out server with a max user limit could work though. But then a dedicated package would be the go-to.

I think transforming this into a package is the way to go and the effect of beeing on cran should not be underestimated. However the `downloadShinyMlr()` solution does not look so well. The files should be part of the package.

**Comment by jakob-r** [comment]
I will make a proposal based on that post: http://stackoverflow.com/questions/37830819/developing-shiny-app-as-a-package-and-deploying-it-to-shiny-server

**Comment by jakob-r** [comment]
My suggest is here #121

**Comment by florianfendt** [comment]
@jakob-r 
great. Thx for your input and your PR. Putting the package into master like this seems indeed more straightforward. 👍

**Comment by jakob-r** [comment]
of course you could also restructure everything and live without linking the files - but i don't know if that makes development easier as it makes most parts of the development more nested. Also I did not want to do this in a PR :wink:

**Comment by florianfendt** [comment]
>I think we would never want to run this on our own server exclusively. If this is supposed to run fast and reliable for many people it's going to be expensive. Who want's to pay for that? A try out server with a max user limit could work though. But then a dedicated package would be the go-to.

Yes, we need a good server solution soon. @berndbischl already mentioned he has contacts where we could possibly host the app. We have a separate Issue for that #11, where we started talking about that.

**Comment by florianfendt** [comment]
Closing here. #121 is merged. Package is now in master ./package.
