### ISSUE TITLE
Error in opening.

### ISSUE THREAD

**Issue by statistician71** [mlr-org/shinyMlr#138]
Hi,
I have watched your videos and this is really cool ! When i tried to open it on my windows, i am facing the following error:

`ERROR: could not find function "..stacktraceon.."`

My system info: windows 7, 64 bit.

**Comment by florianfendt** [comment]
Did you connect to our server or did you Load our package and started the app locally

**Comment by florianfendt** [comment]
And thank you heaps for the feedback :)

**Comment by statistician71** [comment]
I tried locally.

**Comment by statistician71** [comment]
Is there any way to solve this issue

**Comment by Coorsaa** [comment]
we try to find a solution asap!

**Comment by statistician71** [comment]
Thanks a lot. I really appreciate the effort.

**Comment by Coorsaa** [comment]
To at least allow you to have a look at our app you can run it directly from github by following line in the R console:
````shiny::runGitHub('mlr-org/shinyMlr', 'YourGithubAcountName')````
where you put in 'statistician71' instead of 'YourGithubAcountName' of course :)
This works also on my windows machine.

**Comment by statistician71** [comment]
:( Same error !!!

**Comment by Coorsaa** [comment]
thats weird. Can you post your session info?

**Comment by florianfendt** [comment]
@statistician71 
Might be the same problem as this:
https://github.com/rstudio/shiny/issues/1194
Can you tryout the suggestions they give in the issue (e.g: Order of the library calls, switching `library()` to `require()`, maybe put all shiny based packages into the server instead of ui file?
Sorry to be of little help and asking you for this but I can't reproduce on my machine and @Coorsaa either.
Cheers :)

**Comment by statistician71** [comment]
Hi,

Finally i can open:


`require(shiny)
require(shinyjs)
require(shinyBS)
require(DT)
require(plotly)
require(ParamHelpers)
require(mlr)
require(RWeka)
require(farff)
require(OpenML)
require(GGally)

require(shinyMlr)
shiny::runGitHub('mlr-org/shinyMlr', 'YourGithubAcountName')`

But `runShinyMlr()` not working for me. 

Thanks for your such an excellent initiative! 
Last query, will the report saved in a formatted way? Can you please show a sample report on last video section? Thanks :)

**Comment by Coorsaa** [comment]
That's good news! We'll continue to figure out a better way which also works proper on windows machines! Can you give me the error when trying ````runShinyMlr()````? Is is the same as in Issue #126 ?

**Comment by statistician71** [comment]
Yes, the same.

```
> runShinyMlr()

Listening on http://127.0.0.1:7086
Warning: Error in ..stacktraceon..: object '..' not found
Stack trace (innermost first):
    2: runApp
    1: runShinyMlr
Error : object '..' not found
```

**Comment by Coorsaa** [comment]
The report section of the app will improved furthermore in the future so we decided to leave it out in the last video for now. However, when we're happy with it, we will make an update on that ;)

**Comment by statistician71** [comment]
Thanks ! I will keep tracking :+1:

**Comment by Coorsaa** [comment]
okay, so I'll close here now and hope that we'll find a solution for #126 soon and it will solve your original problem automatically
