### ISSUE TITLE
ERROR: could not find function "sidebarMenu" with shinyMLR in R 3.4.1

### ISSUE THREAD

**Issue by heoa** [mlr-org/shinyMlr#141]
I did 

```
devtools::install_github("mlr-org/shinyMlr/package")
shinyMlr::runShinyMlr()
```

and I am getting the error 

> 'ERROR: could not find function "sidebarMenu"'.

**Are there some dependencies such as some shiny packages that are not installed? How to fix this?**

_Specs_

```
Version 1.0.143 – © 2009-2016 RStudio, Inc.

R version 3.4.1 (2017-06-30) -- "Single Candle"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)
```

**Comment by jakob-r** [comment]
Yes. The DESCRIPTION was not updated. sidebarMenu is part of `shinydashboard`.
You should have installed the packages listed in the beginning of [server.R](https://github.com/mlr-org/shinyMlr/blob/master/server.R) and [ui.R](https://github.com/mlr-org/shinyMlr/blob/master/ui.R).

But we should defintely keep the DESCRIPTION up 2 date.

**Comment by Coorsaa** [comment]
should be fixed by the latest commit. Could you please try again @heoa ?

**Comment by heoa** [comment]
Yes it is working, thank you for the quick fix.

![Image about shinyMLR](https://i.stack.imgur.com/G3eLh.png)
