### ISSUE TITLE
META: Will any of you guys present this work on the useR 2017?

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/shinyMlr#60]
Hi,
I think it would be really nice to see this work presented at the useR 2017. What are your thoughts?

**Comment by florianfendt** [comment]
I would totally be up for doing that.
@Coorsaa 
what do you think?

**Comment by berndbischl** [comment]
ok then have a look at the deadlines and talk to me

**Comment by Coorsaa** [comment]
@florianfendt @berndbischl sounds like a pretty good idea to me! Deadline for abstract submissions seems to be April 1, 2017 (http://user2017.brussels/#about).

**Comment by florianfendt** [comment]
Application got sent in. I'll report back here about the status once I hear sth from the organizing committee.
Keep fingers crossed :)

**Comment by Coorsaa** [comment]
Unfortunately we weren't accepted :(
